import Foundation

/// Generates a Fleet GitOps snippet (`fleet-gitops.yml`) on export.
///
/// Fleet accepts DDM declaration `.json` files the same way as `.mobileconfig`
/// profiles, referenced by path under `controls.apple_settings.configuration_profiles`.
/// Our `.ddm.json` files are already in Fleet's expected shape (Type / Identifier
/// / Payload), so this just lists them with the right relative paths for the
/// admin to merge into their Fleet GitOps repo. Still files-only — no API calls.
///
/// Docs: https://fleetdm.com/docs/configuration/yaml-files
public enum FleetGitOps {

    public struct Entry: Sendable {
        public let sourceFile: String      // originating .mobileconfig
        public let relativePath: String    // path to the .ddm.json, relative to the yml
        public let classification: Classification
        public init(sourceFile: String, relativePath: String, classification: Classification) {
            self.sourceFile = sourceFile
            self.relativePath = relativePath
            self.classification = classification
        }
    }

    public static func yaml(entries: [Entry]) -> String {
        var yaml = ""
        yaml += "# Fleet GitOps configuration — generated by DDM Migrator.\n"
        yaml += "#\n"
        yaml += "# Merge the `controls` block below into your Fleet GitOps team YAML\n"
        yaml += "# (e.g. teams/<team>.yml) or default.yml, adjusting the relative paths to match\n"
        yaml += "# your repo layout. Fleet ingests DDM declaration .json files the same way as\n"
        yaml += "# .mobileconfig profiles. Docs: https://fleetdm.com/docs/configuration/yaml-files\n"
        yaml += "#\n"
        yaml += "# NOTE: entries marked \"legacy wrap\" reference com.apple.configuration.legacy with\n"
        yaml += "# a placeholder ProfileURL — host the original .mobileconfig and fill that in, or\n"
        yaml += "# deploy the original profile instead of the declaration.\n"
        yaml += "controls:\n"
        yaml += "  apple_settings:\n"
        yaml += "    configuration_profiles:\n"

        if entries.isEmpty {
            yaml += "      [] # no declarations were produced\n"
            return yaml
        }

        // Group by source file, preserving first-seen order.
        var order: [String] = []
        var grouped: [String: [Entry]] = [:]
        for e in entries {
            if grouped[e.sourceFile] == nil { order.append(e.sourceFile) }
            grouped[e.sourceFile, default: []].append(e)
        }

        for source in order {
            yaml += "      # \(source)\n"
            for e in grouped[source] ?? [] {
                if e.classification == .legacyWrapped {
                    yaml += "      # legacy wrap — replace ProfileURL or deploy the original profile instead:\n"
                }
                yaml += "      - path: \(e.relativePath)\n"
            }
        }
        return yaml
    }
}
